pcap_lookupdev(3PCAP): remove usage
`pcap_lookupdev(3PCAP)` is deprecated:

```
c_src/ewpcap.c: In function ‘nif_pcap_lookupdev’:
c_src/ewpcap.c:394:3: error: ‘pcap_lookupdev’ is deprecated:
 use 'pcap_findalldevs' and use the first device [-Werror=de
precated-declarations]
  394 |   dev = pcap_lookupdev(errbuf);
      |   ^~~
In file included from /usr/include/pcap.h:43,
                 from c_src/ewpcap.c:32:
/usr/include/pcap/pcap.h:328:16: note: declared here
  328 | PCAP_API char *pcap_lookupdev(char *)
      |                ^~~~~~~~~~~~~~
cc1: all warnings being treated as errors
```

The `pcap_lookupdev(3PCAP)` NIF support was only used
internally. `pcap_lookupdev/0` is now a wrapper around
`pcap_findalldevs/0`.